Load naim-0.11.8.3-2006-06-06-2002 into trunk.

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -465,7 +465,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT RANLIB ac_ct_RANLIB CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CXX CXXFLAGS ac_ct_CXX CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL INCLTDL LIBLTDL INSTALL_LTDL_TRUE INSTALL_LTDL_FALSE CONVENIENCE_LTDL_TRUE CONVENIENCE_LTDL_FALSE LIBADD_DL pkgmoddir pkgincludedir pkgtarball cygwindocdir pkgdocdir CYGWIN_TRUE CYGWIN_FALSE INSTALLCYGWINDOC_TRUE INSTALLCYGWINDOC_FALSE NETLIB CURSESLIB LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM mkdir_p AWK SET_MAKE am__leading_dot AMTAR am__tar am__untar CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT RANLIB ac_ct_RANLIB CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os LN_S ECHO AR ac_ct_AR DLLTOOL ac_ct_DLLTOOL AS ac_ct_AS OBJDUMP ac_ct_OBJDUMP CXX CXXFLAGS ac_ct_CXX CXXCPP F77 FFLAGS ac_ct_F77 LIBTOOL INCLTDL LIBLTDL INSTALL_LTDL_TRUE INSTALL_LTDL_FALSE CONVENIENCE_LTDL_TRUE CONVENIENCE_LTDL_FALSE LIBADD_DL pkgmoddir pkgincludedir pkgtarball LUA_TRUE LUA_FALSE cygwindocdir pkgdocdir CYGWIN_TRUE CYGWIN_FALSE INSTALLCYGWINDOC_TRUE INSTALLCYGWINDOC_FALSE NETLIB CURSESLIB LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -1040,6 +1040,7 @@ Optional Features:
   --enable-profile        add profiling to CFLAGS and search for profilable
                           ncurses
   --enable-detach         enable /detach command
+  --enable-lua            Compile experimental Lua scripting support
   --enable-forceascii     enable the $forceascii setting to force alternate
                           line drawing characters
   --disable-dnsupdate     DO NOT allow naim to check for newer versions of
@@ -4866,7 +4867,7 @@ ia64-*-hpux*)
   ;;
 *-*-irix6*)
   # Find out which ABI we are using.
-  echo '#line 4869 "configure"' > conftest.$ac_ext
+  echo '#line 4870 "configure"' > conftest.$ac_ext
   if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
   (eval $ac_compile) 2>&5
   ac_status=$?
@@ -6125,7 +6126,7 @@ fi
 
 
 # Provide some information about the compiler.
-echo "$as_me:6128:" \
+echo "$as_me:6129:" \
      "checking for Fortran 77 compiler version" >&5
 ac_compiler=`set X $ac_compile; echo $2`
 { (eval echo "$as_me:$LINENO: \"$ac_compiler --version </dev/null >&5\"") >&5
@@ -7188,11 +7189,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7191: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7192: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7195: \$? = $ac_status" >&5
+   echo "$as_me:7196: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7456,11 +7457,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7459: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7460: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:7463: \$? = $ac_status" >&5
+   echo "$as_me:7464: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -7560,11 +7561,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:7563: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:7564: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:7567: \$? = $ac_status" >&5
+   echo "$as_me:7568: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -9905,7 +9906,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 9908 "configure"
+#line 9909 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -10005,7 +10006,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 10008 "configure"
+#line 10009 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -12345,11 +12346,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12348: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12349: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:12352: \$? = $ac_status" >&5
+   echo "$as_me:12353: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -12449,11 +12450,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:12452: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:12453: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:12456: \$? = $ac_status" >&5
+   echo "$as_me:12457: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -14019,11 +14020,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14022: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14023: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:14026: \$? = $ac_status" >&5
+   echo "$as_me:14027: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -14123,11 +14124,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:14126: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:14127: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:14130: \$? = $ac_status" >&5
+   echo "$as_me:14131: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -16326,11 +16327,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16329: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16330: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16333: \$? = $ac_status" >&5
+   echo "$as_me:16334: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16594,11 +16595,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16597: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16598: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>conftest.err)
    ac_status=$?
    cat conftest.err >&5
-   echo "$as_me:16601: \$? = $ac_status" >&5
+   echo "$as_me:16602: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s "$ac_outfile"; then
      # The compiler can only warn and ignore the option if not recognized
      # So say no if there are warnings other than the usual output.
@@ -16698,11 +16699,11 @@ else
    -e 's:.*FLAGS}\{0,1\} :&$lt_compiler_flag :; t' \
    -e 's: [^ ]*conftest\.: $lt_compiler_flag&:; t' \
    -e 's:$: $lt_compiler_flag:'`
-   (eval echo "\"\$as_me:16701: $lt_compile\"" >&5)
+   (eval echo "\"\$as_me:16702: $lt_compile\"" >&5)
    (eval "$lt_compile" 2>out/conftest.err)
    ac_status=$?
    cat out/conftest.err >&5
-   echo "$as_me:16705: \$? = $ac_status" >&5
+   echo "$as_me:16706: \$? = $ac_status" >&5
    if (exit $ac_status) && test -s out/conftest2.$ac_objext
    then
      # The compiler can only warn and ignore the option if not recognized
@@ -20694,7 +20695,7 @@ else
   lt_dlunknown=0; lt_dlno_uscore=1; lt_dlneed_uscore=2
   lt_status=$lt_dlunknown
   cat > conftest.$ac_ext <<EOF
-#line 20697 "configure"
+#line 20698 "configure"
 #include "confdefs.h"
 
 #if HAVE_DLFCN_H
@@ -23115,6 +23116,63 @@ else
 
 			echo "$as_me:$LINENO: result: no, re-run ./configure with --enable-detach" >&5
 echo "${ECHO_T}no, re-run ./configure with --enable-detach" >&6
+
+
+fi;
+
+	echo "$as_me:$LINENO: checking whether to enable experimental Lua scripting support" >&5
+echo $ECHO_N "checking whether to enable experimental Lua scripting support... $ECHO_C" >&6
+	# Check whether --enable-lua or --disable-lua was given.
+if test "${enable_lua+set}" = set; then
+  enableval="$enable_lua"
+
+			if test "x${enable_lua}" = xyes; then
+				echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+
+cat >>confdefs.h <<\_ACEOF
+#define ENABLE_LUA 1
+_ACEOF
+
+
+
+if true; then
+  LUA_TRUE=
+  LUA_FALSE='#'
+else
+  LUA_TRUE='#'
+  LUA_FALSE=
+fi
+
+			else
+				echo "$as_me:$LINENO: result: no, you explicitly disabled it" >&5
+echo "${ECHO_T}no, you explicitly disabled it" >&6
+
+
+if false; then
+  LUA_TRUE=
+  LUA_FALSE='#'
+else
+  LUA_TRUE='#'
+  LUA_FALSE=
+fi
+
+			fi
+
+else
+
+			echo "$as_me:$LINENO: result: no, re-run ./configure with --enable-lua" >&5
+echo "${ECHO_T}no, re-run ./configure with --enable-lua" >&6
+
+
+if false; then
+  LUA_TRUE=
+  LUA_FALSE='#'
+else
+  LUA_TRUE='#'
+  LUA_FALSE=
+fi
+
 
 
 fi;
@@ -26277,7 +26335,7 @@ echo ""
 test "$infodir" != '${prefix}/info' || infodir='${datadir}/info'
 test "$mandir" != '${prefix}/man' || mandir='${datadir}/man'
 
-                                                            ac_config_files="$ac_config_files Makefile libfiretalk/Makefile libltdl/Makefile secs/Makefile src/Makefile CYGWIN-PATCHES/Makefile"
+                                                                      ac_config_files="$ac_config_files Makefile libfiretalk/Makefile libltdl/Makefile lua/Makefile secs/Makefile src/Makefile CYGWIN-PATCHES/Makefile"
 
 cat >confcache <<\_ACEOF
 # This file is a shell script that caches the results of configure
@@ -26381,6 +26439,27 @@ if test -z "${CONVENIENCE_LTDL_TRUE}" && test -z "${CONVENIENCE_LTDL_FALSE}"; th
   { { echo "$as_me:$LINENO: error: conditional \"CONVENIENCE_LTDL\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
 echo "$as_me: error: conditional \"CONVENIENCE_LTDL\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${LUA_TRUE}" && test -z "${LUA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"LUA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"LUA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${LUA_TRUE}" && test -z "${LUA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"LUA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"LUA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${LUA_TRUE}" && test -z "${LUA_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"LUA\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"LUA\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
@@ -26842,6 +26921,7 @@ do
   "Makefile" ) CONFIG_FILES="$CONFIG_FILES Makefile" ;;
   "libfiretalk/Makefile" ) CONFIG_FILES="$CONFIG_FILES libfiretalk/Makefile" ;;
   "libltdl/Makefile" ) CONFIG_FILES="$CONFIG_FILES libltdl/Makefile" ;;
+  "lua/Makefile" ) CONFIG_FILES="$CONFIG_FILES lua/Makefile" ;;
   "secs/Makefile" ) CONFIG_FILES="$CONFIG_FILES secs/Makefile" ;;
   "src/Makefile" ) CONFIG_FILES="$CONFIG_FILES src/Makefile" ;;
   "CYGWIN-PATCHES/Makefile" ) CONFIG_FILES="$CONFIG_FILES CYGWIN-PATCHES/Makefile" ;;
@@ -26999,6 +27079,8 @@ s,@LIBADD_DL@,$LIBADD_DL,;t t
 s,@pkgmoddir@,$pkgmoddir,;t t
 s,@pkgincludedir@,$pkgincludedir,;t t
 s,@pkgtarball@,$pkgtarball,;t t
+s,@LUA_TRUE@,$LUA_TRUE,;t t
+s,@LUA_FALSE@,$LUA_FALSE,;t t
 s,@cygwindocdir@,$cygwindocdir,;t t
 s,@pkgdocdir@,$pkgdocdir,;t t
 s,@CYGWIN_TRUE@,$CYGWIN_TRUE,;t t
